import 'package:appnews/domain/entity/suggest_languages/suggest_language_item.dart';

/// LanguageHelper is a class for storing const list of languages.
abstract class LanguageHelper {
  static final List<SuggestLanguageItem> languages = [
    SuggestLanguageItem(label: 'English', code: 'eng'),
    SuggestLanguageItem(label: 'Croatian', code: 'hrv'),
    SuggestLanguageItem(label: 'German', code: 'deu'),
    SuggestLanguageItem(label: 'Spanish', code: 'spa'),
    SuggestLanguageItem(label: 'Catalan', code: 'cat'),
    SuggestLanguageItem(label: 'Portuguese', code: 'por'),
    SuggestLanguageItem(label: 'Italian', code: 'ita'),
    SuggestLanguageItem(label: 'French', code: 'fra'),
    SuggestLanguageItem(label: 'Arabic', code: 'ara'),
    SuggestLanguageItem(label: 'Russian', code: 'rus'),
    SuggestLanguageItem(label: 'Turkish', code: 'tur'),
    SuggestLanguageItem(label: 'Slovenian', code: 'slv'),
    SuggestLanguageItem(label: 'Albanian', code: 'sqi'),
    SuggestLanguageItem(label: 'Serbian', code: 'srp'),
    SuggestLanguageItem(label: 'Macedonian', code: 'mkd'),
    SuggestLanguageItem(label: 'Czech', code: 'ces'),
    SuggestLanguageItem(label: 'Polish', code: 'pol'),
    SuggestLanguageItem(label: 'Slovak', code: 'slk'),
    SuggestLanguageItem(label: 'Irish', code: 'gle'),
    SuggestLanguageItem(label: 'Basque', code: 'eus'),
    SuggestLanguageItem(label: 'Icelandic', code: 'isl'),
    SuggestLanguageItem(label: 'Finnish', code: 'fin'),
    SuggestLanguageItem(label: 'Swedish', code: 'swe'),
    SuggestLanguageItem(label: 'Swiss German', code: 'gsw'),
    SuggestLanguageItem(label: 'Hungarian', code: 'hun'),
    SuggestLanguageItem(label: 'Dutch', code: 'nld'),
    SuggestLanguageItem(label: 'Norwegian Bokmål', code: 'nob'),
    SuggestLanguageItem(label: 'Latvian', code: 'lav'),
    SuggestLanguageItem(label: 'Lithuanian', code: 'lit'),
    SuggestLanguageItem(label: 'Estonian', code: 'est'),
    SuggestLanguageItem(label: 'Georgian', code: 'kat'),
    SuggestLanguageItem(label: 'Bulgarian', code: 'bul'),
    SuggestLanguageItem(label: 'Greek', code: 'ell'),
    SuggestLanguageItem(label: 'Romanian', code: 'ron'),
    SuggestLanguageItem(label: 'Danish', code: 'dan'),
    SuggestLanguageItem(label: 'Azerbaijani', code: 'aze'),
    SuggestLanguageItem(label: 'Kazakh', code: 'kaz'),
    SuggestLanguageItem(label: 'Armenian', code: 'hye'),
    SuggestLanguageItem(label: 'Belarusian', code: 'bel'),
    SuggestLanguageItem(label: 'Ukrainian', code: 'ukr'),
    SuggestLanguageItem(label: 'Korean', code: 'kor'),
    SuggestLanguageItem(label: 'Malay', code: 'mal'),
    SuggestLanguageItem(label: 'Indonesian', code: 'ind'),
    SuggestLanguageItem(label: 'Kurdish', code: 'kur'),
    SuggestLanguageItem(label: 'Persian', code: 'fas'),
    SuggestLanguageItem(label: 'Hebrew', code: 'heb'),
    SuggestLanguageItem(label: 'Thai', code: 'tha'),
    SuggestLanguageItem(label: 'Vietnamese', code: 'vie'),
    SuggestLanguageItem(label: 'Chinese', code: 'zho'),
    SuggestLanguageItem(label: 'Japanese', code: 'jpn'),
    SuggestLanguageItem(label: 'Gujarati', code: 'guj'),
    SuggestLanguageItem(label: 'Tamil', code: 'tam'),
    SuggestLanguageItem(label: 'Kannada', code: 'kan'),
    SuggestLanguageItem(label: 'Urdu', code: 'urd'),
    SuggestLanguageItem(label: 'Hindi', code: 'hin'),
    SuggestLanguageItem(label: 'Punjabi', code: 'pan'),
    SuggestLanguageItem(label: 'Bengali', code: 'ben'),
  ];
}
